### ISSUE TITLE
Other folder icon

### ISSUE THREAD

**Issue by JVariance** [esvres/magico#1]
Could you shortly provide an explanation which parts of the bat file I'd have to change if I'd take another folder icon as base?

For example the new folder icon.
![grafik](https://user-images.githubusercontent.com/62245444/128193677-2b4baea7-5879-484f-975b-f3398a23855e.png)

**Comment by esvres** [comment]
The script first interposes an image of your choice between the front and back of the base folder icon (1), then resizes and moves it to achieve a native-looking feel (2), and finally packages it into an ico file with different resolutions (3).

The solution involves the first two steps:
1. In `\base`, replace `0.png` (back) and `1.png` (front) with the new folder icons. For example, you could use these ones I extracted from Windows 11's `imageres.dll` and converted: [back](https://i.imgur.com/H6wZYh3.png), [front](https://i.imgur.com/xIRWT0x.png).
2. In `run.bat`, you'll have to play around with [geometry](https://github.com/esvres/magico/blob/3b4b180d3706dcac011f2c5223337d533e53f989/run.bat#L4), which defines the size and position of the main picture. Unlike Windows 10's folder icons, here it's all up to personal taste. For example, if you wanted your icons to look like [this](https://i.imgur.com/T621yAA.png), use `set geometry=140x210+38+5`.

Have fun!
